[package]
name = "melior"
description = "The rustic MLIR bindings in Rust"
version = "0.9.9"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/raviqqe/melior"
documentation = "https://raviqqe.github.io/melior/melior/"
readme = "../README.md"
keywords = ["mlir", "llvm"]

[features]
ods-dialects = []

[dependencies]
criterion = "0.5.1"
dashmap = "5.5.0"
melior-macro = { version = "0.4", path = "../macro" }
mlir-sys = "0.2"
once_cell = "1"

[dev-dependencies]
indoc = "2.0.3"
insta = "1.31.0"
pretty_assertions = "1.4.0"

[[bench]]
name = "main"
harness = false
