[package]
name = "melior"
description = "The rustic MLIR bindings in Rust"
version = "0.17.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/raviqqe/melior"
documentation = "https://raviqqe.github.io/melior/melior/"
keywords = ["mlir", "llvm"]

[features]
ods-dialects = []

[dependencies]
dashmap = "5.5.3"
melior-macro = { version = "0.10.3", path = "../macro" }
mlir-sys = "0.2"
once_cell = "1"

[dev-dependencies]
indoc = "2.0.5"
insta = "1.38.0"
pretty_assertions = "1.4.0"
