[package]
name = "melior"
description = "The rustic MLIR bindings in Rust"
version = "0.8.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/raviqqe/melior"
documentation = "https://raviqqe.github.io/melior/melior/"
readme = "../README.md"
keywords = ["mlir", "llvm"]

[dependencies]
criterion = "0.5.0"
melior-macro = { version = "0.3", path = "../macro" }
mlir-sys = "0.2"
once_cell = "1"

[dev-dependencies]
indoc = "2.0.1"
insta = "1.29.0"
pretty_assertions = "1.3.0"

[[bench]]
name = "main"
harness = false
